version: "3.3"

services:

  portainer:
    image: portainer/portainer
    ports:
      - 9000:9000
    command: -H unix:///var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./services/portainer/data:/data
      - '/etc/localtime:/etc/localtime:ro'

  frontvue:
    image: karapazar/angular-serve-light:0.75
    volumes:
      - ./frontend/dist/:/usr/share/nginx/html
      - '/etc/localtime:/etc/localtime:ro'
    networks:
      - frontend-nw
    deploy:
      mode: replicated
      replicas: 1
networks:
  frontend-nw:
