version: "3.3"

services:

  portainer:
    image: portainer/portainer
    ports:
      - 9000:9000
    command: -H unix:///var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./services/portainer/data:/data
      - '/etc/localtime:/etc/localtime:ro'

  frontvue:
    image: karapazar/angular-serve-light:0.75
    volumes:
      - ./frontend/dist/:/usr/share/nginx/html
      - '/etc/localtime:/etc/localtime:ro'
    networks:
            - frontend-nw
    deploy:
            mode: replicated
            replicas: 1
            labels:
                traefik.frontend.rule: "PathPrefix:/"
                traefik.port: "80"
                traefik.enable: "true"
                traefik.docker.network: "frontend-nw"
      
    traefik:
        image: traefik:alpine
        command: -c /etc/traefik.toml
        deploy:
            mode: replicated
            replicas: 1
        ports:
            - "8080:8080"
            - "80:80"
            - target: 443
              published: 443 
              mode: host
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./services/traefik/traefik-stack.toml:/etc/traefik.toml
            - ./services/traefik/data/traefik.log:/etc/traefik.log
            - ./services/traefik/data/traefik-access.log:/etc/traefik-access.log
            - ./services/traefik/self.crt:/etc/self.crt
            - ./services/traefik/self.key:/etc/self.key
            - '/etc/localtime:/etc/localtime:ro'
        networks:
            - frontend-nw
